% byebye.m
% credit info

pause(0.5)
printf("%s", YEL)
disp("\t                              ****************************************")
disp("\t                              ***                                  ***")
disp("\t                              ***       titrationSimulator         ***")
disp("\t                              ***                                  ***")
disp("\t                              ****************************************")
disp("\t                              ***      powered by GNU Octave       ***")
disp("\t                              ****************************************")
disp("")                              
disp("\t                              ++++++++++++++++++++++++++++++++++++++++")
disp("\t                              ++         DO THE PEAKS MOVE?         ++")
disp("\t                              ++++++++++++++++++++++++++++++++++++++++")
disp("\t                              ++ (c)2026    HvI Utrecht University ++")
disp("\t                              ++++++++++++++++++++++++++++++++++++++++")

p=0.25;  % to make sure appearance takes 1 sec = 0.5 bar

disp("")
printf("%s", MAG)
typewriter("\t                     THANKS TO ECEM ARPI AND ALL STUDENTS THAT GAVE FEEDBACK", 0.05)
disp("")
typewriter("\t\t                                HOPE YOU ENJOYED IT", 0.05)
disp("")
typewriter("\t\t                             GOOD LUCK WITH YOUR EXAM IN", 0.05)
typewriter(" ....", 0.1)
disp("")
printf("%s", CYN)
disp("")
disp("")
disp("\t       ::::    ::: :::    :::  ::::::::  :::        ::::::::::     :::     :::::::::   ")
disp("\t       :+:+:   :+: :+:    :+: :+:    :+: :+:        :+:          :+: :+:   :+:    :+:  ")
pause(p)
disp("\t       :+:+:+  +:+ +:+    +:+ +:+        +:+        +:+         +:+   +:+  +:+    +:+  ")
disp("\t       +#+ +:+ +#+ +#+    +:+ +#+        +#+        +#++:++#   +#++:++#++: +#++:++#:   ")
pause(p)
disp("\t       +#+  +#+#+# +#+    +#+ +#+        +#+        +#+        +#+     +#+ +#+    +#+  ")
disp("\t       #+#   #+#+# #+#    #+# #+#    #+# #+#        #+#        #+#     #+# #+#    #+#  ")
pause(p)
disp("\t       ###    ####  ########   ########  ########## ########## ###     ### ###    ###  ")
disp("")
pause(p*4)
disp("\t   ::::    ::::      :::      ::::::::  ::::    ::: :::::::::: ::::::::::: ::::::::::: ::::::::   ")
disp("\t   +:+:+: :+:+:+   :+: :+:   :+:    :+: :+:+:   :+: :+:            :+:         :+:    :+:    :+:  ")
pause(p)
disp("\t   +:+ +:+:+ +:+  +:+   +:+  +:+        :+:+:+  +:+ +:+            +:+         +:+    +:+         ")
disp("\t   +#+  +:+  +#+ +#++:++#++: :#:        +#+ +:+ +#+ +#++:++#       +#+         +#+    +#+         ")
pause(p)
disp("\t   +#+       +#+ +#+     +#+ +#+   +#+# +#+  +#+#+# +#+            +#+         +#+    +#+         ")
disp("\t   #+#       #+# #+#     #+# #+#    #+# #+#   #+#+# #+#            #+#         #+#    #+#    #+#  ")
pause(p)
disp("\t   ###       ### ###     ###  ########  ###    #### ##########     ###     ########### ########   ")
disp("")
pause(p*4)
disp("\t:::::::::  :::::::::: ::::::::   ::::::::  ::::    :::     :::     ::::    :::  ::::::::  ::::::::::  ")
disp("\t:+:    :+: :+:       :+:    :+: :+:    :+: :+:+:   :+:   :+: :+:   :+:+:   :+: :+:    :+: :+:         ")
pause(p)
disp("\t+:+    +:+ +:+       +:+        +:+    +:+ :+:+:+  +:+  +:+   +:+  :+:+:+  +:+ +:+        +:+         ")
disp("\t+#++:++#:  +#++:++#  +#++:++#++ +#+    +:+ +#+ +:+ +#+ +#++:++#++: +#+ +:+ +#+ +#+        +#++:++#    ")
pause(p)
disp("\t+#+    +#+ +#+              +#+ +#+    +#+ +#+  +#+#+# +#+     +#+ +#+  +#+#+# +#+        +#+         ")
disp("\t#+#    #+# #+#       #+#    #+# #+#    #+# #+#   #+#+# #+#     #+# #+#   #+#+# #+#    #+# #+#         ")
pause(p)
disp("\t###    ### ########## ########   ########  ###    #### ###     ### ###    ####  ########  ##########  ")
disp("")
printf("%s", WHT)
pause(0.5)
% start intro music
player = audioplayer(chordTrack, fs);
% t = 0  time start
play(player)
disp("Bye bye")
disp("")
pause(16)
disp("Wait, some happy cosines to finish off with ...")
disp("")
% start intro music
player = audioplayer(soloTrack, fs);
% t = 0  time start
play(player)
pause(32)
exit
