% listCommands.m

disp("")
disp("You can enter the following commands at the prompt:")
disp("      - listCommands      : view this help info")
disp("      - makeSample        : make a (new) sample")
disp("      - rpar              : load an NMR dataset")
disp("      - zg                : start an NMR experiment")
disp("      - xfb               : process a 2D spectrum")
disp("      - edlev             : change contouring of the spectra")
disp("      - plotAll           : replot all titration spectra")
disp("      - zoomPeak          : zoom in on a peak in the spectra")
disp("      - zoomFull          : show full spectrum after zooming in")
disp("      - coneView          : show a 3D mesh plot of current 2D spectrum")
disp("      - report            : print overview of titration steps")
disp("      - titrate           : add more ligand to your sample")
disp("      - calcCSP           : calculate chemical shift perturbations")
disp("      - getKD             : fit the dissociation constant")
disp("      - saveResults       : save the final results")
disp("      - unAdd             : remove the last ligand addition to the sample")
disp("      - saveState         : save all titration data")
if easyMode < 2
disp("      - qfp               : process a 1D spectrum")
disp("      - eda               : edit the acquisition parameters")
disp("      - showFID           : show the 2D free induction decay")
disp("      - reduceOverlay     : reduce the number of spectra in the overlay")
disp("      - overlayAll        : undo reduceOverlay")
disp("      - showSlices        : show 1D projections for a peak")
end
disp("")
